declare class EditGroup extends eui.Group {
    displayList: any[];
    tool: any;
    maskTool: TransformTool;
    pages: any[];
    pageIndex: number;
    private borderColor;
    displayGroup: eui.Group;
    private siderbar;
    constructor();
    protected createChildren(): void;
    private onAddToStage(event);
    private bindHandlers();
    private initEui();
    private getPages();
    private init();
    setupTool(): void;
    getCustomControls(): EgretControl[];
    down(event: egret.TouchEvent): boolean;
    move(event: egret.TouchEvent): void;
    up(event: egret.TouchEvent): void;
    private setProperty(x?, y?);
    applyDynamicControls(event: any): void;
    getDynamicControl(): any;
    findControlByType(type: any): any;
    containsPoint(x: number, y: number): boolean;
    select(event: PageEvent): void;
    selectImage(x: number, y: number): boolean;
    renderResources(index: number): Promise<void>;
    render(): void;
    renderOneDisplay(): void;
    clear(): void;
    reset(): void;
    drawDisplayList(): void;
    pre(event: egret.TouchEvent): void;
    next(event: egret.TouchEvent): void;
    go(event: PageEvent): void;
    updateDisplay(display: Picture): void;
    updateDisplayProps(display: Picture): void;
    triggerMaskById(imageId: any): void;
    addResource(data: uiData, uutype: number): void;
    addSound(data: uiData): void;
    addPage(): void;
    addResource1(type: number, d?: uiData): Promise<void>;
}
