declare class SiderbarSkinBy extends eui.Component implements IUUContainer {
    container: Game;
    dispose(): void;
    draw(container: any): void;
    private gp_tabs;
    private gp_eventContainers;
    private gp_container_addEvent;
    private btn_add_event;
    private gp_add_click_event;
    private gp_eventContainer_event_click;
    private gp_selection_rect;
    private gp_selection_box;
    private gp_selection;
    private gp_eventSetContainer;
    private gp_inputContainer;
    private input_width;
    private btn_update;
    private scroller_eventSet;
    private color_AEEEEE;
    private color_000000;
    private _selectionVisible;
    selectionVisible: boolean;
    private _targetItemId;
    targetItemId: number;
    private _triggerGroup;
    triggerGroup: Array<any>;
    private relevanceItemIdList;
    private _relevanceItemIdObj;
    relevanceItemIdObj: Object;
    private defaultRelevanceItem;
    data: Object;
    private static _instance;
    static getInstance(): SiderbarSkinBy;
    private _tabIndex;
    tabIndex: number;
    private isFirstSelect;
    constructor();
    private onAddToStageInit(event);
    private init();
    private listenEvent();
    private touchTabsClick(evt);
    private touchAddEvent(evt);
    private addClickEventItem(evt);
    private touchSelection2();
    private onMouseover_Selection(evt);
    private onClick_Selection(evt);
    private drawEventSet(eventSetMessage);
    private pushEventSet(eventSetMessage);
    removeEventSet(eventSetMessage: any): void;
    private setupEventSetContainer();
    private initShowEventSetList();
    private onFocusOut(evt);
    private activetedTab(tab);
    private unActivetedTab(tab);
    private cleanTab();
    private cleanContainer();
    private changeTabIndex(index);
}
